accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'account'
urlpatterns = [
    path('signup', views.signup_page_view, name='signup'),
    path('login', views.login_page_view, name='login'),
    path('logout', views.logout_page_view, name='logout'),
    path('contact-us', views.contact_us_page_view, name='contact_us'),
    path('success', views.success_page_view, name='success'),
    path('profile', views.profile_page_view, name='profile'),
    path('edit-profile', views.edit_profile_page_view, name='edit_profile'),
]

course/urls.py
from django.urls import path
from course import views

app_name = 'course'
urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('create/', views.CreateCoursePageView.as_view(), name='create_course'),
    path('panel/', views.panel_page_view, name='panel'),
]

django_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/', include('course.urls', namespace='course')),
    path('account/', include('accounts.urls', namespace='account')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}University{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'apple.ico' %}">
</head>
<body>
<div dir="rtl">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'course:home' %}">صفحه نخست <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:contact_us' %}">ارتباط با ما </a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">خروج </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:profile' %}">نمایه </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'course:panel' %}">مدیریت کارها </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">ورود </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:signup' %}">ثبت نام </a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </nav>
</div>

<div class="container" dir="rtl" style="margin: 20px auto;">
    {% block breadcrumb %}
    {% endblock %}
    <di>
        {% block content %}
        {% endblock %}
    </di>
</div>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <h2>ارتباط با ما</h2>
    <form {% url 'account:contact_us' %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-block mb-4">ثبت درخواست</button>
    </form>
    <div style="color:red;">
        {% for error in form.errors.values %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/create_course.html
{% extends 'base.html' %}

{% block content %}
    <div class="card-body">
        <h5 class="card-title">اطلاعات پروفایل</h5>
    </div>

    <form action="{% url 'course:create_course' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-block mb-4">ایجاد </button>
    </form>

    <div style="color:red;">
        {% for error in form.errors.values %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="card-body">
        <h5 class="card-title">اطلاعات پروفایل</h5>
    </div>

    <form action="{% url 'account:edit_profile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" href="{% url 'account:edit_profile' %}" class="btn btn-primary btn-block mb-4">ثبت
        </button>
    </form>

    <div style="color:red;">
        {% for error in form.errors.values %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block breadcrumb %}
    <p>سلام. به سامانه انتخاب واحد مجازی خوش آمدید.</p>
{% endblock %}

templates/login.html
{% extends 'base.html' %}


{% block breadcrumb %}
    <h1 dir="rtl" class="breadcrumb-item active">ورود</h1>
{% endblock %}
{% block content %}
    <form action={% url 'account:login' %} method="post">
        {% csrf_token %}
        <!-- Email input -->
        <div class="form-outline mb-4">
            <input type="text" id="form2Example1" name="username" class="form-control"/>
            <label class="form-label" for="form2Example1">نام کاربری </label>
        </div>
        <!-- Password input -->
        <div class="form-outline mb-4">
            <input type="password" id="form2Example2" name="password" class="form-control"/>
            <label class="form-label" for="form2Example2">رمز عبور </label>
        </div>
        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">ورود</button>
    </form>
    <div style="color:red;">
        {% for error in form.errors.values %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/panel.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <table class="table">
            <thead class="thead-inverse">
            <tr>
                <th>دانشکده</th>
                <th>نام</th>
                <th>شماره گروه</th>
                <th>شماره درس</th>
                <th>نام استاد</th>
                <th>ساعت شروع</th>
                <th>ساعت پایان</th>
                <th>روز اول</th>
                <th>روز دوم</th>
            </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.department }}</td>
                    <td>{{ course.name }}</td>
                    <td>{{ course.group_number }}</td>
                    <td>{{ course.course_number }}</td>
                    <td>{{ course.teacher_name }}</td>
                    <td>{{ course.start_time }}</td>
                    <td>{{ course.end_time }}</td>
                    <td>{{ course.display_first_day }}</td>
                    <td>{{ course.display_second_day }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% if request.user.is_superuser %}
        <a href="{% url 'course:create_course' %}" class="btn btn-primary btn-block mb-4">ایجاد واحد </a>
    {% endif %}

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load blog_extras %}


{% block content %}
    {% if request.user.avatar %}
        <div class="form-outline mb-4" style="display: flex;">
            <img class="card-img-top" src="{{ request.user.avatar.url }}" alt="connect"
                 style="height: 9rem;width: 9rem;border-radius: 50%;margin: auto;">
        </div>
    {% endif %}
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">نام کاربری </label>
        <input value="{{ request.user.username }}" type="text" id="form2Example1" name="username"
               class="form-control" disabled/>
    </div>
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">نام </label>
        <input value="{{ request.user.first_name }}" type="text" id="form2Example1" name="username"
               class="form-control" disabled/>
    </div>
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">نام خانوادگی </label>
        <input value="{{ request.user.last_name }}" type="text" id="form2Example1" name="username"
               class="form-control" disabled/>
    </div>
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">جنسیت</label>
        <input value="{{ request.user.display_gender }}" type="text" id="form2Example1" name="username"
               class="form-control" disabled/>
    </div>
    <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">زندگینامه</label>
        {{ request.user.bio | convert_markdown | safe }}
    </div>

    <a href="{% url 'account:edit_profile' %}" class="btn btn-primary btn-block mb-4">ویرایش</a>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>ثبت نام</h2>
    <form {% url 'account:signup' %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-block mb-4">ثبت نام</button>
    </form>
    <div style="color:red;">
        {% for error in form.errors.values %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% block content %}
    <div style="color:green;">
        <h1>درخواست شما ثبت شد.</h1>
    </div>
{% endblock %}